### ISSUE TITLE
Does not work in browsers with no support for ES6

### ISSUE THREAD

**Issue by matheussilvasantos** [rodrigoyoshida/async-await-foreach#1]
### Steps to reproduce
Create a project using the addon.

### Expected behavior
It should work in old browsers that do not support ES6.

### Actual behavior
It breaks because of `async` and `let` statements.

**Comment by rodrigoyoshida** [comment]
This issue was solved on 1.0.3 version.

Thank you for your contribution sir. We are happy to serve you.

**Comment by matheussilvasantos** [comment]
Thank you very much. I'm so glad with your help.
